#!/bin/bash

# The purpouse of this is to ignore the /build directory when pushing to version control, and not having to use git subtree
# The Heroku repository is in a separate folder from our version control dev folder
# Avoids a bunch of headaches (very nice)

(cd client; npm run build) # Build our frontent
# rm -r  won't deleting hidden files, so our .git folder is safe
rm -r ../heroku-files/* # To avoid keeping files that aren't used anymore
cp -r server/* ../heroku-files  # Copy over our server content with it's build/ folder
rm -r ../heroku-files/node_modules  # Remove node modules, will be installed automatically when deployed
(cd ../heroku-files; git add .; git commit -m'new version'; git push) # Push it to heroku
