# Compose file for production
version: '3.8'

services:
  app:
    image: sandsten/portfolio:latest
    # '127.0.0.1:3000:3000' will ensure port 3000 is only exposed to host and not remote
    # Remote access should be handled by Nginx instead!
    ports:
      - '127.0.0.1:3000:3000'
    environment:
      DATABASE: remote
      NODE_ENV: production
      PORT: 3000
    secrets:
      - my_secrets

secrets:
  my_secrets:
    file: ./secrets.txt