version: '3'

services:
  # Node backend
  app:
    image: test:2
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - NODE_ENV=production
      - SERVER=remote

    # Mongo database
# Volumes for mongo database
