type Thumbnails = Record<string, string>;

export const thumbnails: Thumbnails = {
	"anki-hgg-added.webp": '../assets/images/thumbnails/anki-hgg-added.webp',
	"away-from-home.webp": '../assets/images/thumbnails/away-from-home.webp',
	"bandmate.webp": '../assets/images/thumbnails/bandmate.webp',
	"banner-soundark.webp": '../assets/images/thumbnails/banner-soundark.webp',
	"bear-with-me.webp": '../assets/images/thumbnails/bear-with-me.webp',
	"birch-tree.webp": '../assets/images/thumbnails/birch-tree.webp',
	"bosh-maxx-7-varioperfect-how-to-turn-off-the-beeping-poster.webp": '../assets/images/thumbnails/bosh-maxx-7-varioperfect-how-to-turn-off-the-beeping-poster.webp',
	"braun-series-3-battery-replacement-poster.webp": '../assets/images/thumbnails/braun-series-3-battery-replacement-poster.webp',
	"crowdsim.webp": '../assets/images/thumbnails/crowdsim.webp',
	"driving-in-vr.webp": '../assets/images/thumbnails/driving-in-vr.webp',
	"driving-simulator-v1-thumbnail.webp": '../assets/images/thumbnails/driving-simulator-v1-thumbnail.webp',
	"godball.webp": '../assets/images/thumbnails/godball.webp',
	"haptic-curling.webp": '../assets/images/thumbnails/haptic-curling.webp',
	"lastShip.webp": '../assets/images/thumbnails/lastShip.webp',
	"lion.webp": '../assets/images/thumbnails/lion.webp',
	"per-albin.webp": '../assets/images/thumbnails/per-albin.webp',
	"plex-logo.webp": '../assets/images/thumbnails/plex-logo.webp',
	"portfolio-thumbnail.webp": '../assets/images/thumbnails/portfolio-thumbnail.webp',
	"poster-version-2.webp": '../assets/images/thumbnails/poster-version-2.webp',
	"shooting-range.webp": '../assets/images/thumbnails/shooting-range.webp',
	"soundark.webp": '../assets/images/thumbnails/soundark.webp',
	"storylines.webp": '../assets/images/thumbnails/storylines.webp',
	"thesis-thumbnail.webp": '../assets/images/thumbnails/thesis-thumbnail.webp',
	"tracking-cards.webp": '../assets/images/thumbnails/tracking-cards.webp',
	"webgl.webp": '../assets/images/thumbnails/webgl.webp',
}