name: Upload to Digitalocean droplet

# When something new is pushed to the master branch
on:
  push:
    branches:
      master

env:
  NODE_VERSION: '12.x' # Node version on digitalocean server

jobs:
  build: # Job name, can be anything
    # Run on our self hosted runner on our droplet. 
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: npm install, build
        run: |
          npm install 
          npm run build
      # TODO: If this is successfull, 
    