name: Create a docker image, save it on docker hub and deploy it on my home server

on:
  push:
    branches: docker

jobs:
  build:
    # Specify which self hosted runner to use
    # Has to match all tags. The last one is a custom one whic I created
    # Choose the runner on my home server
    runs-on: [self-hosted, linux, x64, home]

    steps:
    - name: Checkout docker branch
      uses: actions/checkout@v2
      with:
        ref: docker
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push to DockerHub
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64,linux/386
        push: true
        tags: sandsten/portfolio-website:latest
