name: Create a docker image, save it on docker hub and deploy it on my home server

on:
  push:
    branches: main

# on:
#   release:
#     types: ["published"]

jobs:
  build:
    # Specify which self hosted runner to use
    # Has to match all tags. The last one is a custom one whic I created
    # Choose the runner on my home server
    runs-on: [self-hosted, linux, x64, home]

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push to DockerHub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-website:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
